version: '3'

networks:
  my-network:
    driver: bridge

services:
  n1:
    image: tzeikob/replica
    container_name: n1
    restart: "no"
    networks:
      - my-network
    ports:
      - 27017:27017
    volumes:
      - ./data/n1:/data/db
    command: --port 27017 --replSet rs0

  n2:
    image: tzeikob/replica
    container_name: n2
    restart: "no"
    networks:
      - my-network
    ports:
      - 27018:27018
    volumes:
      - ./data/n2:/data/db
    command: --port 27018 --replSet rs0

  n3:
    image: tzeikob/replica
    container_name: n3
    restart: "no"
    networks:
      - my-network
    ports:
      - 27019:27019
    volumes:
      - ./data/n3:/data/db
    command: --port 27019 --replSet rs0